CREATE TABLE IF NOT EXISTS user_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    event_id BIGINT,
    score DOUBLE PRECISION,
    interact_at TIMESTAMP,
    UNIQUE(user_id, event_id)
);

CREATE TABLE IF NOT EXISTS event_similarity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_A_id BIGINT,
    event_B_id BIGINT,
    score DOUBLE PRECISION,
    calculated_at TIMESTAMP,
    UNIQUE (event_A_id, event_B_id)
);