logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        cache:
          use_query_cache: false
          use_second_level_cache: false
    show-sql: true
  messages:
    basename: test-messages
  security:
    enabled: false
  sql:
    init:
      mode: never

server:
  port: 0

stats-server:
  id: stats-server