services:
  discovery-server:
    build:
      context: ./infra/discovery-server
      dockerfile: Dockerfile
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - explore-network
    healthcheck:
      test: "curl --fail --silent discovery-server:8761/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 20s
      retries: 5

  config-server:
    build:
      context: ./infra/config-server
      dockerfile: Dockerfile
    container_name: config-server
    depends_on:
      discovery-server:
        condition: service_healthy
    networks:
      - explore-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SERVER_PORT=9091
    healthcheck:
      test: "curl --fail --silent config-server:9091/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 30s
      retries: 5

  gateway-server:
    build:
      context: ./infra/gateway-server
      dockerfile: Dockerfile
    container_name: gateway-server
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_healthy
      ewm-service:
        condition: service_healthy
    networks:
      - explore-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/

  analyzer-db:
    image: postgres:16.1
    container_name: analyzer-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ewm_analyzer_db
    ports:
      - "5433:5432"
    networks:
      - explore-network
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 10s
      retries: 15


  ewm-event-db:
    image: postgres:16.1
    container_name: postgres-event-db
    restart: always
    environment:
      - POSTGRES_DB=ewm_event_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "6432:5432"
    networks:
      - explore-network
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 10s
      retries: 15

  ewm-comment-db:
    image: postgres:16.1
    container_name: postgres-comment-db
    ports:
      - "6433:5432"
    environment:
      - POSTGRES_DB=ewm_comment_db
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 10s
      interval: 10s
      retries: 15
    networks:
      - explore-network

  ewm-request-db:
    image: postgres:16.1
    container_name: postgres-request-db
    ports:
      - "6434:5432"
    environment:
      - POSTGRES_DB=ewm_request_db
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 10s
      interval: 10s
      retries: 15
    networks:
      - explore-network

  ewm-user-service:
    build: core/user-service
    container_name: ewm-user-service
    depends_on:
      ewm-event-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
    networks:
      - explore-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-event-db:5432/ewm_event_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SERVER_PORT=8082
    healthcheck:
      test: "curl --fail --silent localhost:8082/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 25s
      retries: 10

  ewm-service:
    build: ./core/event-service
    container_name: ewm-service
    restart: always
    depends_on:
      ewm-event-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-event-db:5432/ewm_event_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SERVER_PORT=8081
    healthcheck:
      test: "curl --fail --silent localhost:8081/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 25s
      retries: 10
    networks:
      - explore-network

  ewm-comment-service:
    build: core/comment-service
    container_name: ewm-comment-service
    depends_on:
      ewm-comment-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
    networks:
      - explore-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-comment-db:5432/ewm_comment_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SERVER_PORT=8083
    healthcheck:
      test: "curl --fail --silent localhost:8083/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 25s
      retries: 10

  ewm-request-service:
    build: core/request-service
    container_name: ewm-request-service
    depends_on:
      ewm-request-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
    networks:
      - explore-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-request-db:5432/ewm_request_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SERVER_PORT=8087
    healthcheck:
      test: "curl --fail --silent localhost:8087/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 25s
      retries: 10

  kafka:
    image: confluentinc/confluent-local:7.4.3
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092" # for client connections
      - "9101:9101" # JMX
    restart: unless-stopped
    networks:
      - explore-network
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: kafka
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      CLUSTER_ID: 'K0EA9p0yEe6MkAAAAkKsEg'

  kafka-init-topics:
    image: confluentinc/confluent-local:7.4.3
    container_name: kafka-init-topics
    networks:
      - explore-network
    depends_on:
      - kafka
    command: "bash -c \
                'kafka-topics --delete --topic stats.user-actions.v1 --bootstrap-server kafka:29092 --if-exists && \
                 kafka-topics --delete --topic stats.events-similarity.v1 --bootstrap-server kafka:29092 --if-exists && \
                 kafka-topics --create --topic stats.user-actions.v1 \
                              --partitions 1 --replication-factor 1 --if-not-exists \
                              --bootstrap-server kafka:29092 && \
                 kafka-topics --create --topic stats.events-similarity.v1 \
                              --partitions 1 --replication-factor 1 --if-not-exists \
                              --bootstrap-server kafka:29092'"
    init: true

  collector:
    build: stats/collector
    container_name: collector
    restart: on-failure
    depends_on:
      config-server:
        condition: service_healthy
      kafka-init-topics:
        condition: service_completed_successfully
      aggregator:
        condition: service_healthy
    networks:
      - explore-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/


  aggregator:
    build: stats/aggregator
    container_name: aggregator
    restart: on-failure
    networks:
      - explore-network
    depends_on:
      config-server:
        condition: service_healthy
      kafka-init-topics:
        condition: service_completed_successfully
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SERVER_PORT=8085
    healthcheck:
      test: "curl --fail --silent localhost:8085/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 25s
      retries: 10

  analyzer:
    build: stats/analyzer
    container_name: analyzer
    restart: on-failure
    depends_on:
      analyzer-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      kafka-init-topics:
        condition: service_completed_successfully
    networks:
      - explore-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://analyzer-db:5432/ewm_analyzer_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SERVER_PORT=8086
    healthcheck:
      test: "curl --fail --silent localhost:8086/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 25s
      retries: 10


networks:
  explore-network:
    driver: bridge
