server:
  port: 8761

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    server:
      waitTimeInMsWhenSyncEmpty: 0
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/