spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
        - id: main_service_route
          uri: lb://main-service
          predicates:
            - Path=/categories/**,/users/**,/comments/**,/events/**,/compilations/**,/admin/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

server:
  port: 8080