server:
  port: 0

spring:
  application:
    name: stats-server
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://stats-db:5432/ewm_stats_db
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always